### ISSUE TITLE
Change page background and console background

### ISSUE THREAD

**Issue by kpalway** [cs136/seashell#139]
All we would need for this is a "dark mode" to contrast the current light mode.

**Comment by zanwenhuahao** [comment]
Hey Ed

The dark mode by separating the CSS information is done, for the default version, much of the colour information is still in the common.css, I tried to remove colour information from there and put into NormalThemeColour.css, and leave all the structure information in a newcommon.css but stuff keeps breaking. I’m going to sort through the common.css again and remove the colour information so the default theme can be broken down too.

I’ve committed and pushed (to my own repository? it’s zanwenhuahao-patch-2) how do I push/commit so that you can see it?

I’ve changed removed a few inline css in some places (notably the seashell logo) and changed them into CSS ids.

Let me know what I should do.

Tappy

**Comment by zanwenhuahao** [comment]
Changed pop up menu(s) to dark theme
