### ISSUE TITLE
Implement git features: commit, revert

### ISSUE THREAD

**Issue by kpalway** [cs136/seashell#142]
This has been requested by students several times. I can't recall if we decided this would be too confusing or not.

**Comment by kcolford** [comment]
If you can at least enable the commit feature, then you can add in a help message describing it as "Saving a Snapshot of your current project, so that if something goes wrong then the staff [or you] can can restore it to the way it was before.  Leave a descriptive message so that when you go back, you know which backup is the one you want."

Also, the commit feature is very important because otherwise you leave all edits as uncommited changes in the repository, which means you can't fix (and therefore can't realistically distribute) object files from the skeleton repository for an assignment.  This is becuase git-pull uses git-merge, and from the man page of git-merge(1):

>**Warning**: Running git merge with non-trivial uncommitted changes is
>discouraged: while possible, it may leave you in a state that is hard
>to back out of in the case of a conflict.

Which means that if the user has edited any of the files in a way that would cause a conflict, you can't just use the merge strategy "ours" to keep the user code there since it isn't even in the index to begin with.

I'm putting together a patch right now for this, it seems you already have most of the code needed to make it happen, so I'll send a pull request soon.

**Comment by e45lee** [comment]
It's probably a sensible thing to also commit on/before each submission to Marmoset.

**Comment by e45lee** [comment]
We have decided to not use git after all.  I am closing this issue to reflect this.
