### ISSUE TITLE
Allow setting a file in common as runner file

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#471]

**Comment by yc2lee** [comment]
I created this on Kanban flow

**Comment by yc2lee** [comment]
@e45lee Hey Ed I noticed that you cannot create a file named X in the question folder if X is already in common/. BUT if X is in the question folder, you can still create X in the common folder. Is this intentional?

Basically I'm asking if the same filename can appear in a question folder and in the common folder.

**Comment by YLiLarry** [comment]
We can't prevent instructors from updating the common folder because the student has the same filename though.

Larry

**Comment by YLiLarry** [comment]
It's more like I didn't care about that case when I wrote the script. If you want to prevent in two directions, we can always find a work around.
