### ISSUE TITLE
Deleting file -> unable to pull from skeleton file

### ISSUE THREAD

**Issue by yc2lee** [cs136/seashell#815]
On the new Seashell if you delete a file it boots you back to the project list with an error message

**Comment by kpalway** [comment]
As of yesterday's fixes, it actually does pull the skeleton file after it is deleted. However, it still has the behaviour that it kicks you back to the home screen when this happens. This is because it sees a change from the server, and assumes that someone is editing the file in another tab/browser. I will try to think of a reasonable workaround.

**Comment by e45lee** [comment]
The reducer will need to do something more intelligent.  One thing you could do is have the code that applies the server change compute the changes for each project, and pass that along to the reducer, so it can update the UI properly.

**Comment by e45lee** [comment]
See #794.
